version: "3"

services:
  api-gateway:
    container_name: kong
    image: kong:2.6.0-alpine
    ports:
      - 8001:8001
      - 8000:8000
      - 8443:8443
    env_file: 
      - ./.env
    volumes: 
      - ./config:/usr/local/kong/declarative