version: "3"

services:
  database:
    container_name: auth-database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env